# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

xcodeproj 'GADIDemo'

pod 'GoogleAnalytics-iOS-SDK'
pod 'MOAspects'
